### ISSUE TITLE
sequence diagrams

### ISSUE THREAD

**Issue by vilasmamidyala** [vilasmamidyala/Project_MP#5]
creating sequence diagrams for music player

**Comment by vilasmamidyala** [comment]
milestone added

**Comment by dineshkumar1994** [comment]
![seq_login](https://cloud.githubusercontent.com/assets/16810150/13192742/05fab0e2-d735-11e5-85ad-16b6ab0b0a9b.png)
![seq_logout](https://cloud.githubusercontent.com/assets/16810150/13192743/05fab09c-d735-11e5-8252-ca180e39e1ee.png)
![seq_mp](https://cloud.githubusercontent.com/assets/16810150/13192745/05fd46f4-d735-11e5-8c7f-eeb5f67f415f.png)
![seq_mp2](https://cloud.githubusercontent.com/assets/16810150/13192744/05fc5ac8-d735-11e5-8ae8-8925b115db75.png)

**Comment by dineshkumar1994** [comment]
done sequence diagram in visio
