### ISSUE TITLE
state diagrams

### ISSUE THREAD

**Issue by vilasmamidyala** [vilasmamidyala/Project_MP#6]
state diagrams for music player

**Comment by vilasmamidyala** [comment]
milestone added

**Comment by RanjithaReddyB** [comment]
![state_login](https://cloud.githubusercontent.com/assets/16810642/13192781/68104922-d735-11e5-9836-6c83400f4014.png)
![state_logout](https://cloud.githubusercontent.com/assets/16810642/13192783/68132584-d735-11e5-972e-55af7f682841.png)
![state_register](https://cloud.githubusercontent.com/assets/16810642/13192782/68131206-d735-11e5-9ed6-d5270ce74163.png)

**Comment by RanjithaReddyB** [comment]
DONE STATE DIAGRAMS
